DROP TABLE "USER";
DROP TABLE ROOM;
DELETE FROM "USER";
DELETE FROM ROOM;



CREATE TABLE IF NOT EXISTS ROOM (
  id        INT PRIMARY KEY,
  room_name VARCHAR(255)
);
CREATE TABLE IF NOT EXISTS "USER" (
id          INT PRIMARY KEY,
name        VARCHAR(255),
room_number INTEGER ,
FOREIGN KEY (room_number) REFERENCES ROOM(id) ON DELETE CASCADE
);